### ISSUE TITLE
AzureGroupDeploymentCreate SetNoWait should not require any parameters

### ISSUE THREAD

**Issue by JleruOHeP** [nuke-build/azure#22]
Current workaround - 
`.SetNoWait("")`

**Comment by arodus** [comment]
Thanks for raising the issues. The fix should be soon available in nuget. 
Since the addon is auto generated and contains about 2000 tasks it's nearly impossible to test every single one of them. I'll try to find a more reliable way to get the argument types, but until then I'm happy about every issue about wrong types ;)

**Comment by JleruOHeP** [comment]
Hey, no worries!
I checked the code - and yep, it is hard :)
And thank you for your work - like this library!
